CREATE TABLE EMPLOYEE
 ( EMPNO 	VARCHAR2(8) NOT NULL,
  EMPNAME	VARCHAR(50) NOT NULL,
  DEPARTMENT	VARCHAR(50) NOT NULL,
  EMAIL		VARCHAR(50) NOT NULL,
  PHONE		CHAR(6) NOT NULL,
CONSTRAINT PKempno PRIMARY KEY (EMPNO)
  );
CREATE TABLE CUSTOMER
  ( CUSTNO VARCHAR2(8) NOT NULL,
  CUSTNAME VARCHAR(50)NOT NULL,
  ADDRESS VARCHAR(50)NOT NULL,
  INTERNAL CHAR(1) DEFAULT 'Y' NOT NULL,
  CONTACT VARCHAR(50)NOT NULL,
  PHONE CHAR(7)NOT NULL,
  CITY VARCHAR(50)NOT NULL,
  STATE CHAR(2)NOT NULL,
  ZIP CHAR(5) DEFAULT '80217' NOT NULL,  
CONSTRAINT PKcustno  PRIMARY KEY (CUSTNO)
  );
 CREATE TABLE RESOURCETBL
 (RESNO VARCHAR2(8) NOT NULL,
 RESNAME VARCHAR(50)NOT NULL,
 RATE DECIMAL(2,0) NOT NULL CHECK (RATE > 0),
 CONSTRAINT PKresno  PRIMARY KEY (RESNO)
 );
CREATE TABLE FACILITY
 (FACNO VARCHAR2(8) NOT NULL,
 FACNAME VARCHAR(50)NOT NULL,
 CONSTRAINT PKfacno  PRIMARY KEY (FACNO),
 CONSTRAINT Uniquefacname UNIQUE (FACNAME)
 );
 CREATE TABLE LOCATIONTBL
 (LOCNO VARCHAR2(8) NOT NULL,
 FACNO VARCHAR2(8) NOT NULL,
 LOCNAME VARCHAR(50)NOT NULL,
 CONSTRAINT PKlocno  PRIMARY KEY (LOCNO),
 CONSTRAINT FKfacno FOREIGN KEY (FACNO) REFERENCES FACILITY(FACNO)
 );
 CREATE TABLE EVENTREQUEST
  (EVENTNO VARCHAR2(8) NOT NULL,
  DATEHELD DATE NOT NULL,
  DATEREQ DATE DEFAULT SYSDATE NOT NULL,
  CUSTNO VARCHAR2(8) NOT NULL,
  FACNO VARCHAR2(8) NOT NULL,
  DATEAUTH DATE,
  STATUS VARCHAR(50)DEFAULT 'Pending' NOT NULL CHECK (STATUS in ('Pending','Denied','Approved')),
  ESTCOST DECIMAL(10,0) NOT NULL,
  ESTAUDIENCE INTEGER NOT NULL CHECK (ESTAUDIENCE > 0),
  BUDNO VARCHAR(50),
 CONSTRAINT CKdate CHECK ((DATEAUTH > DATEREQ)OR(DATEAUTH IS NULL)),
 CONSTRAINT PKeventno  PRIMARY KEY (EVENTNO),
 CONSTRAINT FKcusno FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER(CUSTNO),
 CONSTRAINT FKfacnoevent FOREIGN KEY (FACNO) REFERENCES FACILITY (FACNO)
  );
 CREATE TABLE EVENTPLAN 
  (PLANNO VARCHAR2(8) NOT NULL,
  EVENTNO VARCHAR2(8) NOT NULL,
  WORKDATE DATE NOT NULL,
  NOTES VARCHAR(50),
  ACTIVITY VARCHAR(50)NOT NULL,
  EMPNO VARCHAR2(8),
  CONSTRAINT PKplanno  PRIMARY KEY (PLANNO),
  CONSTRAINT FKeventno FOREIGN KEY (EVENTNO) REFERENCES EVENTREQUEST (EVENTNO) ON DELETE CASCADE ,
  CONSTRAINT FKempno FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE(EMPNO)
  );
  CREATE TABLE EVENTPLANLINE 
  (PLANNO VARCHAR2(8) NOT NULL,
  LINENO VARCHAR2(8) NOT NULL,
  TIMESTART DATE NOT NULL,
  TIMEEND DATE NOT NULL,
  NUMBERFLD INTEGER NOT NULL,
  LOCNO VARCHAR2(8)NOT NULL,
  RESNO VARCHAR2(8)NOT NULL,
  CONSTRAINT CKtime CHECK (TIMEEND > TIMESTART),
  CONSTRAINT PKplanline PRIMARY KEY (PLANNO,LINENO),
  CONSTRAINT FKplanno FOREIGN KEY (PLANNO) REFERENCES EVENTPLAN(PLANNO)ON DELETE CASCADE ,
  CONSTRAINT FKlocno FOREIGN KEY (LOCNO) REFERENCES LOCATIONTBL(LOCNO),
  CONSTRAINT FKresno FOREIGN KEY (RESNO) REFERENCES RESOURCETBL(RESNO) 
  );
