@@ -0,0 +1,98 @@
Query Formulation Part 1 Problems (25%)
1.	
SELECT DISTINCT city, state, zip
FROM CUSTOMER;

2.	
SELECT EMPNAME,department,phone,email
FROM EMPLOYEE
WHERE phone like '3-%';

3.	
SELECT *
FROM RESOURCETBL
WHERE RATE between 10 and 20
ORDER BY RATE;

4.	
SELECT EVENTNO ,DATEAUTH ,STATUS
FROM EVENTREQUEST
WHERE DATEAUTH between '1-jul-2013' and '31-jul-2013'
and STATUS = 'Approved' or STATUS = 'Denied';

5.	
SELECT LOCNO, LOCNAME
FROM LOCATIONTBL, FACILITY
WHERE LOCATIONTBL.FACNO = FACILITY.FACNO
and FACILITY.FACNAME = 'Basketball arena';

Query Formulation Part 2 Problems (50%)
6.
SELECT PLANNO, COUNT(LINENO) AS Lines, sum(NUMBERFLD) AS Number_of_Resources
FROM EVENTPLANLINE
GROUP BY PLANNO;

7. Join 2 tables
SELECT EVENTREQUEST.EVENTNO, DATEHELD,count(EVENTPLAN.PLANNO) AS EventPlans
FROM EVENTREQUEST, EVENTPLAN
WHERE EVENTREQUEST.EVENTNO = EVENTPLAN.EVENTNO
and EVENTPLAN.WORKDATE between '1-dec-2013' and '31-dec-2013'
GROUP BY EVENTREQUEST.EVENTNO, DATEHELD
having count(EVENTPLAN.PLANNO) > 1;

8.	Join 3 tables
SELECT EVENTPLAN.PLANNO,EVENTPLAN.EVENTNO,WORKDATE,ACTIVITY
FROM (EVENTREQUEST inner join FACILITY  on FACILITY.FACNO = EVENTREQUEST.FACNO )
inner join EVENTPLAN  on EVENTREQUEST.EVENTNO = EVENTPLAN.EVENTNO
WHERE  EVENTPLAN.WORKDATE between '1-dec-2013' and '31-dec-2013'
and FACILITY.FACNAME = 'Basketball arena';

9.	Join 4 tables
SELECT EVENTREQUEST.EVENTNO, DATEHELD,STATUS,ESTCOST
FROM EVENTREQUEST, EVENTPLAN, EMPLOYEE, FACILITY
WHERE EVENTREQUEST.EVENTNO = EVENTPLAN.EVENTNO
and EVENTPLAN.EMPNO = EMPLOYEE.EMPNO
and EVENTREQUEST.FACNO = FACILITY.FACNO
and EMPLOYEE.EMPNAME = 'Mary Manager'
and FACILITY.FACNAME = 'Basketball arena'
and EVENTREQUEST.DATEHELD between '1-oct-2013' and '31-dec-2013';

10.	Join 5 tables
SELECT EVENTPLANLINE.PLANNO,EVENTPLANLINE.LINENO,RESNAME,NUMBERFLD AS Number_of_Resources,LOCNAME,TIMESTART,TIMEEND
FROM EVENTPLANLINE, RESOURCETBL, LOCATIONTBL, FACILITY, EVENTPLAN
WHERE  EVENTPLANLINE.PLANNO = EVENTPLAN.PLANNO
and EVENTPLANLINE.RESNO = RESOURCETBL.RESNO
and EVENTPLANLINE.LOCNO = LOCATIONTBL.LOCNO
and LOCATIONTBL.FACNO = FACILITY.FACNO
and FACILITY.FACNAME = 'Basketball arena'
and EVENTPLAN.ACTIVITY = 'Operation'
and EVENTPLAN.WORKDATE between '1-oct-2013' and '31-dec-2013';

--Database Modification Problems (25%)
--1.	
INSERT into FACILITY (FACNO, FACNAME)
VALUES ('F104' , 'Swimming Pool');

--2.	
INSERT into LOCATIONTBL (LOCNO,FACNO, LOCNAME)
VALUES ('L107','F104','Gate');

--3.	
INSERT into LOCATIONTBL (LOCNO,FACNO, LOCNAME)
VALUES ('L108','F104','Locker Room');

--4.	
UPDATE LOCATIONTBL
set LOCNAME = 'Door' WHERE FACNO in (SELECT FACNO FROM facility WHERE FACNAME ='Swimming Pool');

--5.First,I had deleted the swimming pool facility in the LOCATIONTBL table , then I deleted it in the FACILITY table.

DELETE FROM LOCATIONTBL
WHERE FACNO in
(SELECT LOCATIONTBL.FACNO
FROM LOCATIONTBL inner join FACILITY ON LOCATIONTBL.FACNO = FACILITY.FACNO
WHERE FACILITY.FACNAME = 'Swimming Pool');

DELETE FROM FACILITY
WHERE FACNAME = 'Swimming Pool';
